version: "3.9"
services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/api
    ports:
      - 8000:8000
    env_file:
      - ./recuirt/.env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=recuirt
      - POSTGRES_PASSWORD=r3cu1rt.c4p1t4l
      - POSTGRES_DB=recuirt

volumes:
  postgres_data:
