# Generated by Django 4.2 on 2023-07-07 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(through='nafasi.ExperienceWeight', to='nafasi.skill')),
            ],
        ),
        migrations.AddField(
            model_name='experienceweight',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafasi.position'),
        ),
        migrations.AddField(
            model_name='experienceweight',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafasi.skill'),
        ),
    ]
