# Generated by Django 4.2 on 2023-07-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafasi', '0002_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceweight',
            name='experience_time',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
            preserve_default=False,
        ),
    ]
