# Generated by Django 4.2 on 2023-07-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafasi', '0003_experienceweight_experience_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='max_candidates',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
